[project]
name = "shellpower"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pyautogui>=0.9.54",
    "pydantic>=2.12.1",
    "pythonnet>=3.0.5",
    "pywin32>=311",
]

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "pillow>=12.1.0",
    "scipy>=1.18.1",
    "tdqm>=0.0.1",
]

[tool.uv]
package = true
